package:
  name: lightcones
  version: "0.0.1"
build:
  number: 0
source:
  path: ../lightcones
requirements:
  host:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - python
    - numpy
    - scipy
    - meson
    - ninja
  run:
    - python
    - numpy
    - scipy
outputs:
  - name: lightcones